### ISSUE TITLE
zoo data analysis

### ISSUE THREAD

**Issue by itchyshin** [itchyshin/castration_meta-analysis#16]
@Mike-Garratt - I got around to doing the zoo data with lnRR (no phylogeny is incorporated yet).

# Male surgical
## lnRR (life expectancy)
![04d8aa6f-0fa1-4b2c-ba64-e741960556ec](https://user-images.githubusercontent.com/12078523/163763836-15a64659-3423-4602-a95d-ec1fbc979583.png)

## lnHR (risk of death)
![79294a1f-ecbd-4435-ac1c-8a9e07cbea93](https://user-images.githubusercontent.com/12078523/163763840-bfb96cbb-664a-49e0-9251-f8d2af841412.png)

# Female hormonal
## lnRR (life expectancy)
![83f3cb6d-c7bc-4542-a7d2-96b0c9d75a45](https://user-images.githubusercontent.com/12078523/163763862-b2773da6-d11c-4aad-a2ef-8291d21083d2.png)

## lnHR (risk of death)
![a5f540a0-f6af-49cd-9fe0-bc9fdaa321c7](https://user-images.githubusercontent.com/12078523/163763893-2e849182-29dd-4050-a200-2f05b70b48bd.png)

# Female surgical
## lnRR (life expectancy)
![7def42dd-f0d8-45ac-98e7-d8179de30d8f](https://user-images.githubusercontent.com/12078523/163763906-0e6eda0c-d693-4a29-8d45-cec5cae52230.png)

## lnHR (risk of death)
![db40ddff-d898-468e-9f57-52b66244515e](https://user-images.githubusercontent.com/12078523/163763928-45d53c3e-c4ad-4523-9759-3e30cb1afc70.png)

More to come - now will work on the new analysis of our meta-analysis data

**Comment by itchyshin** [comment]
@Mike-Garratt - I re-opened this - things to talk about today

- what analyses to do 
- what figures to create (I can redo Fig 5)
- I am confused with some figs in the text (ask some questions)
- what else?

**Comment by itchyshin** [comment]
Things to do for @itchyshin 

- [ ] create the sex difference figure with a tree for the zoo data (work with @Jeff-Lemaitre and @mlagisz )
- [ ] finish off meta-analyses for zoo data (life expectancy)
- [ ] make sure to do the same for the rate of aging
- [ ] put all the analyses and figures into the HTML (work with Fernando)

**Comment by itchyshin** [comment]
Updating the list after a meeting with @Mike-Garratt 

- [ ] Contact Johanna to get the fig for Fig 1
- [ ] recreate Fig 1 & 5
- [ ] Analyses pre and post data

**Comment by itchyshin** [comment]
@Mike-Garratt - some new analyses 

There is a clear outlier (male possums) 

I will do more and also - try to do figs as you wanted with a phylo tree.

As you see below - all effects are very consistent

Overall effect is as much as 28% (excluding possums - 20%)

## Overall

![Screenshot 2023-09-02 at 8 29 42 pm](https://github.com/itchyshin/castration_meta-analysis/assets/12078523/5ca90c7b-5d10-4e99-bba6-75ba663aa417)

# Sex 
![b79f0bc0-8922-4084-b189-1a96064a5084](https://github.com/itchyshin/castration_meta-analysis/assets/12078523/1439d0a6-b548-43eb-82fb-71814ea01dc4)

# Type of Castration
![fa8c2d2d-eb8e-49ef-9cbf-4e757f52d1bb](https://github.com/itchyshin/castration_meta-analysis/assets/12078523/3da12148-1c7a-4b4a-9bf1-8e8c9d160219)

# Sex x Type 
![Screenshot 2023-09-02 at 8 24 19 pm](https://github.com/itchyshin/castration_meta-analysis/assets/12078523/826ff437-dea5-43ae-a797-b6b92f929a86)

**Comment by itchyshin** [comment]
Here are risk-of-death analysis @Mike-Garratt 

Some of the slopes (risk) seem to have SE too narrow or precision is too high compared to others (we may need to ask Fernando to check?)

These are - "Procavia capensis" (hyrax)  "Suricata suricatta"  (meerkat)

## Overal

![2ccdd611-4cec-4699-b987-92f1a6d63005](https://github.com/itchyshin/castration_meta-analysis/assets/12078523/0a4e3b7c-1363-4093-8251-12f2b874bce1)

## Sex 
![020cf190-a2a4-45d6-b91e-2e960ef79bf6](https://github.com/itchyshin/castration_meta-analysis/assets/12078523/865baa2a-9155-4968-a037-764cab646a14)

## Type of castration
![64cb6806-ff2e-4232-bb14-912321900ec3](https://github.com/itchyshin/castration_meta-analysis/assets/12078523/f383bd1d-5d01-45a1-b3eb-990c26170b95)

## Sex x Type
![cfa02378-fc55-48b5-af43-fdad12e3a95d](https://github.com/itchyshin/castration_meta-analysis/assets/12078523/1cb32915-ac80-40c2-96d0-cd5c21f078cc)

## Correaliton between lifespan and risk of death

![9d5b2039-04cc-43f2-bba0-87df17dd7549](https://github.com/itchyshin/castration_meta-analysis/assets/12078523/3d9def66-c324-47c2-b8f9-6429a5546e25)

**Comment by itchyshin** [comment]
Things to chat with @Mike-Garratt 

- [ ] what to do with the outlier (possum)
- [ ] what to do with the risk of death analysis (some outliers in terms of precision or SE)

Things still to do for @itchyshin 

- [ ] pre-post analysis
- [ ] Fig 1 & 5
- [ ] HTLM including everything (need to decide what to put)

**Comment by Mike-Garratt** [comment]
Hi @itchyshin 

Thanks for sending this through! I had noticed the possum outlier as well and think that we should exclude this as it must be a mistake in the database somewhere, so a problem with the zoo data.

I didnt realize the had already got slope data from Fernando. I am not sure about these outliers, I don't see a problem with excluded them all will we need to highlight this in the methods and so it will be good to check with Fernando at some point.

Are you all good with the plan for the figures? If you want to set up a time to chat then let me know, I am pretty free this week.

Thanks for your work on this!

Mike

**Comment by itchyshin** [comment]
@Mike-Garratt - thanks for your replies. 

Let me work on the figs and other analyses next 2 days (I will update you here), and we can set a meeting mid or later in the coming week.

**Comment by itchyshin** [comment]
@Mike-Garratt - I am sorry for the slow progress (I am putting all the time but some data matching and checking is taking me long). I have found that Elk is not in the tree - in the tree, it is the same as Red Deer so I will get @mlagisz's help to get this added to the tree (I think for the currently fig, it was just deleted). I am hoping that I can get some preliminary fig for Fig 1 and the analysis for Fig 5 done today

**Comment by itchyshin** [comment]
This needs to be resolved (@mlagisz - we will chat soon)

![Screenshot 2023-09-06 at 8 58 17 am](https://github.com/itchyshin/castration_meta-analysis/assets/12078523/fe9e0554-1134-4a31-8722-ed72454a82ef)

**Comment by Mike-Garratt** [comment]
Thanks @itchyshin , sorry sounds like a pain. Let me know if I can help! Mike

**Comment by itchyshin** [comment]
@Mike-Garratt - nearly there
![plot_zoom_png](https://github.com/itchyshin/castration_meta-analysis/assets/12078523/b1b58cfe-7924-4be5-a754-9b5becd19a8c)

**Comment by itchyshin** [comment]
@Mike-Garratt - one of the package (ggtree) seems a bit broken so I cannot recreate what Johanna did but I will ask her for help a bit later - I am moving onto other analyses (abs analyses, fig 5 and pre-post). The image quality seems a bit low - I will look into later (this package seems to have a lot of issues so I cannot really figure out a lot of things for now).

![plot_zoom_png-2](https://github.com/itchyshin/castration_meta-analysis/assets/12078523/fcd8697a-c9ff-4132-9377-d869b6a7b9b5)

**Comment by Mike-Garratt** [comment]
Thanks Shinichi, annoying about the image resolution but otherwise it looks amazing! Some of the surgical effects in males are very strong...thanks for all your work and please let me know if I can help!

**Comment by itchyshin** [comment]
@Mike-Garratt - these really high ones are usually from low sample sized studies- we could add orchard plots like Fig 2 so people know spp estimates are based on very different sample sizes (precisions)

**Comment by Mike-Garratt** [comment]
Hi @itchyshin , yes that might be good. They do seem like very large increases in life-expectancy. I did look at the original plot of wallabia bicolor, which I think is one of the big ones, and the increase looks biologically plausible. 
[Wallabia_bicolor.pdf](https://github.com/itchyshin/castration_meta-analysis/files/12555152/Wallabia_bicolor.pdf)

**Comment by itchyshin** [comment]
@Mike-Garratt with phylogeny - I will do one with absolute values now (but I have to figure out contrast first)

![plot](https://github.com/itchyshin/castration_meta-analysis/assets/12078523/7cbde6be-89c3-4614-8747-23cb83cc99b9)

**Comment by itchyshin** [comment]
Absolute ones - not done stats but they look all the same (chat tomorrow)

![plot copy](https://github.com/itchyshin/castration_meta-analysis/assets/12078523/fad4d12f-4bd1-44d0-965d-a3ef9d9b549d)

**Comment by itchyshin** [comment]
@Mike-Garratt - I have added all the contrasts for both analyses above

**Comment by itchyshin** [comment]
# pre and post analyses

They are consistent in terms of effect size (seems a bit small) - pre is not sig as small sample size
![bb7a6e4b-6ad9-4bae-807a-c0b9059d6a51](https://github.com/itchyshin/castration_meta-analysis/assets/12078523/a7786914-a699-4785-ae9c-6932c14db64c)
