### ISSUE TITLE
To do list (1 June 2020)

### ISSUE THREAD

**Issue by itchyshin** [itchyshin/castration_meta-analysis#18]
@Mike-Garratt 

- [x] work on the MS a bit more
- [x] send @mlagisz a sketch of the idea diagrams

@mlagisz 

- [x] work on conceptual diagrams (based on Mike's sketch)
- [x]  read the MS again once @itchyshin works on it
- [x] finish off the method section - search-related things

@itchyshin 

- [x] carefully read the MS
- [x] create - figs 1-4 (also figure legends)
- [x] add statistics to the text
- [x] write Stats methods etc
- [x] the first draft for Suppl
- [x] finalise Suppl Materials

All

- [x] PRISMA-EcoEvo checklist (to submit to Nat Comm)

**Comment by itchyshin** [comment]
@Mike-Garratt - here is the MS with my comments

[Castration.meta.analysis.4.270722_SN.docx](https://github.com/itchyshin/castration_meta-analysis/files/9225503/Castration.meta.analysis.4.270722_SN.docx)

Also, the HTML file - but this can also be accessed by

[index.html.zip](https://github.com/itchyshin/castration_meta-analysis/files/9225504/index.html.zip)

https://itchyshin.github.io/castration_meta-analysis

And importantly, I had to make this repository public so now people can access this, and this is a good thing

**Comment by Mike-Garratt** [comment]
Thanks guys, I appreciate you looking at this so quickly. Just at the airport about to fly from the USA to the UK. I'll see if I can look at this tomorrow and maybe send a final version to other authors.

Do you have any ideas for reviewers? I think the other authors may and I have some ideas for biology of aging people.

Hope all is well

Mike

________________________________

**Comment by itchyshin** [comment]
@Mike-Garratt  - the MS looks great! (if we can do PRISMA-EcoEvo in the next round it will be fantastic).

I think Steven Austad is great - he understands the importance of comparative work 

https://scholar.google.com/citations?user=8HPaM2oAAAAJ&hl=en

For meta-analysis reviewers, they are great 

https://scholar.google.co.uk/citations?user=Iy8gDgEAAAAJ&hl=en

https://scholar.google.com/citations?user=DG_zZLYAAAAJ&hl=en

Bt they will certainly expect us to have an PRISMA-EcoEvo checklist done - as I have seen them using it.

So it may be a good idea to do it - it will probably only take you 30 min extra - @mlagisz can help you, and you can submit the check list along with the MS

https://prisma-statement.org/Extensions/EcoEvo

The word version or excel version is easy to use.

**Comment by Mike-Garratt** [comment]
Hi @itchyshin, thanks for the comments and making the supplementary figure. For S1, I think that the Y axis title for A and C are incorrect. These are the female comparisons so should be male normal/female sterilized. Would it be possible for you to update this?

Yep, Steve Austad is a good idea!

**Comment by Mike-Garratt** [comment]
Hey @itchyshin and @mlagisz 

I havent started prepping the checklist yet - happy for us to do it if you think we need to. There may be a few things that we haven't done - can we just not tick these? We have just arrived in the UK and things are a bit hectic, so might not be able to get to it for a couple of days.

Hope all is well

Mike

**Comment by itchyshin** [comment]
@Mike-Garratt 

Yes, it will have some NOs - this is why I want you to fill it in - once done, I can check and see whether we can actually add a few things and turn it around to YES (this is the main function of check-list - we tend to forget things). But something would be difficult to put in (e.g. limitation in abstract).

Also, I will try to fix S1 fig soon as soon as I get it (the final week of teaching - lots fo assignments and things are coming in).

**Comment by Mike-Garratt** [comment]
Hi @itchyshin @mlagisz 
I have filled in the Prisma checklist. I have highlighted a couple of questions where I wasnt sure of the answer. Do you want to give it a check over? We had done the vast majority of the things.
Hope all is well,

Mike
[EcoEvo_WordChecklist.docx](https://github.com/itchyshin/castration_meta-analysis/files/9239643/EcoEvo_WordChecklist.docx)
!

**Comment by itchyshin** [comment]
@Mike-Garratt 

The fixed 
[figS1.tiff.zip](https://github.com/itchyshin/castration_meta-analysis/files/9248161/figS1.tiff.zip)

@mlagisz - gone through the checklist - I am now going through it and also will update the HTML (and the website). 

And let you know.

**Comment by itchyshin** [comment]
@Mike-Garratt - letting you know that 

I will edit the docx file named "Castration.meta.analysis.6.010822.docx" in "Third draft" folder in relation to the checklist

Also, relevant documents I am putting into the folder called "fourth draft documents to submit"

**Comment by itchyshin** [comment]
@Mike-Garratt - @mlagisz and I have gone through the checklist - commented version is in "fourth draft documents to submit". I have done as much as I can - there are several things you can add and do - none of them should be difficult. If not clear, please ask us. Thanks!

**Comment by Mike-Garratt** [comment]
Hi @itchyshin @mlagisz , Sorry I have just had covid since arriving in the UK. 

I think we have everything sorted now. Are you guys happy for me to submit when I think everything is ready? I just need to check through the documents and check everything is together.
Cheers
Mike

**Comment by itchyshin** [comment]
@Mike-Garratt - Yes, Losia and I are fine to you submit - thanks for doing this.
