### ISSUE TITLE
Plan to finalise the MS (12 Sept 2023)

### ISSUE THREAD

**Issue by itchyshin** [itchyshin/castration_meta-analysis#20]
@Mike-Garratt and @itchyshin had a meeting and discussed what is left to do

- [x] @itchyshin checks the ones with >150% extension
- [x] Make Fig 1 nicer - get @mlagisz'e help 
- [x] Create Fig 4 like Fig 1 @itchyshin + @mlagisz  (make sure we combine all types of sterilizations)
- [ ] Get @mlagisz to check Fig 1 and 4
- [ ] Create an HTML (a separate one from the meta-analysis one, which is completed already) for the Zoo analyses, including all figs and tables - pre-post (but leave Gamma stuff for now as we do not discuss this in the main text). 
- [x] Add stats to the MS - @itchyshin and then get @Mike-Garratt to check (@itchyshin - adding to @Jeff-Lemaitre's version)
- [x] Get the final list of authors - @Mike-Garratt 
- [ ] Probably @Mike-Garratt and @itchyshin have a meeting again once @itchyshin finishes his part
- [x] @Mike-Garratt send enquires to Science/Nature editors

@Mike-Garratt if I forget something please do add (If I have questions, I will email you and double-check)

**Comment by itchyshin** [comment]
## Fig 1

![plot_zoom_png-5](https://github.com/itchyshin/castration_meta-analysis/assets/12078523/c816fa73-9b9a-46a4-a820-4c7973af184c)


## Fig 4

![plot_zoom_png-7](https://github.com/itchyshin/castration_meta-analysis/assets/12078523/61c940ff-194f-406c-9c2e-dae18a03cd86)


@Mike-Garratt - I realise that I have to redo the HTML as fig numbers etc changed, I have some issues with old code not running (very common issues with R), it may take a while for me to resolve). Also, this is last 2 weeks in Okinawa and they are jam-pakced with meetings and workshops. 

Now I am adding stats etc but I realise to be consistent we need to discuss what to do with suppl. figs etc (reporting of heterogeneity - zoo data has I2 etc as well). So once I do what I can do for now I will set a meeting.

**Comment by Mike-Garratt** [comment]
Thanks Shinichi, these figures look awesome!  I think as long we have the made statistics in the manuscript we should be good and we can match up the stats between the two types of analysis at a later point.  

Have you already started working on a copy of the manuscript? I was going to address Jeff's comments but don't want to start a conflicted version. 

Hope you can enjoy your last couple of weeks in Okinawa, sounds like a great experience.

Mike

**Comment by itchyshin** [comment]
@Mike-Garratt - thanks for your reply - I will email you the current version
